### ISSUE TITLE
Support new oauth

### ISSUE THREAD

**Issue by ujovlado** [keboola/tde-exporter#13]
Ked si nanovo autorizujem napr. google drive, tak tde exported saha stale do  stareho oauth vyzera to tak.

A potom to konci s errorom:

```
OAuth API error: No data found for api: keboola.wr-google-drive with id: tde-484908993 in project xxx
```

**Comment by kacurez** [comment]
rychly braindump:

- bude treba upravit auth object ktory sa vytvara pre konfig pri uploade do google drive writeru alebo dropbox writeru tu:
https://github.com/keboola/tde-exporter/blob/a2ff656e192f20a6dbe2734396dd5c0027a9924e/src/uploadTasks.py#L40-L48
- treba upravit ui aby ukladalo version:3 oauth.
- bude sa to musiet rucne zmigrovat - uprava migracneho ui aby zobrazoval konfig ktory treba zmigrovat(reautorizovat) rucne

**Comment by ujovlado** [comment]
Nefici to ... v credentials je totiz aj `folder`.

**Comment by ujovlado** [comment]
To bude zase 💡
