### ISSUE TITLE
migration of upload components using oauth

### ISSUE THREAD

**Issue by kacurez** [keboola/tde-exporter#3]
### Sucasny stav
- na google drive je pouzity stary writer 
- na dropbox je pouzity dropbox writer ktory ma stary oauth(=nesifrovane data na komponentu, potrebuje len id credentials)
- user autorizuje ucet(dropbox, google drive) priamo cez config tableau writeru(aka tde-exporter)
- v konfigu tde-exporteru su ulozene access tokeny(zasifrovane) resp. id credentials
- tableu online writer ma ulozene zasifrovane credentials v konfigu(nepotrebuje oauth)

### Problem
- ~novy google drive writer => novy oauth => neni mozne ulozit id credentials resp access token do konfigu tde-exporteru~
- je to mozne ulozit pretoze id credentials nieje nijak zviazane s id configu takze sa to da autorizovat z ui tde-exporteru

### Riesenie
Do konfigu tde-exporteru sa ulozi id konfigu google-drive/dropbox writeru cez ktory sa pusti upload do gdrive/dropbox. 

#### pros
- user "globalne" vidi(v zlozke writerov) writer ktory sa pouzije na upload
- bezpecne
- umozni uplne vypnut/deprekovat stary google drive writer ktory pouziva sys buckety
- uvolni cestu k deprekacii stareho oauth ktory pouziva dropbox writer
- jednoduchsie ui(neni nutne implementovat autorizaciu na ui tde-exporteru)

#### cons
- ux - trocha zlozitejsie na konfiguraciu
- switch v ui na novy sposob vyberu uploadu
- migracia - stare komponenty(gdrive dropbox) nechame bezat ale casom to bude treba zmigrovat(asi len rucne), TODO: zistit ako velmi sa upload do gdrive/dropbox pouziva

**Comment by odinuv** [comment]
no a jak jsme se teda dohodli s tim chainovanim?

**Comment by kacurez** [comment]
@odinuv imo nepadlo rezolutne rozhodnutie.
tu to riesim hlavne kvoli tomu aby sa mohol deprekovat stary gdrive writer ako nejjednoduchsie mozne technicke riesenie.

**Comment by ondrejhlavacek** [comment]
taky si myslim, že se to ještě nerozhodlo. imo se to asi bude muset nějak vyzkoušet. píšu si a příští týden zkusím vykopnout, jak by mohla vypadat konfigurace pro chainovanou komponentu

**Comment by kacurez** [comment]
len doplnim ze debata prebehla tu https://github.com/keboola/docker-bundle/issues/175

**Comment by kacurez** [comment]
upload komponenty gdrive a dropbox su zmigrovane najjednoduchsim moznym sposobom tj robi sa to po starom ze v konfigu tde-exporteru je ulozene credentiasld dropbox/gdrive writeru a upload pusti tu komponentu s danym credentialsId, vacsie upravy boli urobene na ui.
https://github.com/keboola/tde-exporter/pull/7

tu to zavriem pretoze problem zmigrovania starych writerov je tym vyrieseny. Hned ako to bude mozne sa to potom moze prerobit na chainovanie komponent.

https://github.com/keboola/tde-exporter/pull/7
